# Generated by Django 3.1.7 on 2021-03-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'managestore_data_source',
            },
        ),
        migrations.CreateModel(
            name='Manage_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source_name', models.TextField(max_length=30)),
                ('file_name', models.TextField(max_length=30)),
                ('execution_time', models.TextField(default=None, max_length=30)),
                ('number_of_records', models.IntegerField(default=None)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageStore.data_source')),
            ],
            options={
                'db_table': 'managestore_manage_store',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_idd', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('country', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('category', models.TextField(max_length=100)),
                ('sub_category', models.TextField(max_length=100)),
                ('product_name', models.TextField(max_length=100)),
                ('sales', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
                ('profit', models.FloatField()),
                ('manage_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageStore.manage_store')),
            ],
            options={
                'db_table': 'managestore_data',
            },
        ),
    ]
